name: saas_warehouse_analytics_pipeline
version: "1.0.0"
config-version: 2

profile: saas_warehouse_analytics_pipeline

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]

models:
  saas_warehouse_analytics_pipeline:
    +materialized: view
    staging:
      +schema: ravenstack_stg
    core:
      +schema: ravenstack_core
      +materialized: table
    marts:
      +schema: ravenstack_marts
      +materialized: table
    audit:
      +schema: ravenstack_audit
      +materialized: table

seeds:
  saas_warehouse_analytics_pipeline:
    +schema: ravenstack_raw
    +quote_columns: false